from dotmap import DotMap

CONFIG_DEFAULTS = DotMap(
    {
        "dimensions": {
            "display_height": 2480,
            "display_width": 1640,
            "processing_height": 820,
            "processing_width": 666,
        },
        "threshold_params": {
            "GAMMA_LOW": 0.7,
            "MIN_GAP": 30,
            "MIN_JUMP": 25,
            "CONFIDENT_SURPLUS": 5,
            "JUMP_DELTA": 30,
            "PAGE_TYPE_FOR_THRESHOLD": "white",
        },
        "alignment_params": {
            # Note: 'auto_align' enables automatic template alignment, use if the scans show slight misalignments.
            "auto_align": False,
            "match_col": 5,
            "max_steps": 20,
            "stride": 1,
            "thickness": 3,
        },
        "pdf_params": {
            "pdf_dpi": "auto",
            "pdf_page": 1,
        },
        "weak_mark_params": {
            "enabled": False,
            "min_gap": 10,
            "min_delta_from_blank": 25,
            "adaptive_min_delta_from_blank": 12,
            "min_delta_from_page_blank": 20,
            "min_page_z_score": 2.0,
            "min_dark_pixel_ratio": 0.08,
            "min_density_gap": 0.03,
            "conflict_use_density": True,
            "conflict_min_density_gap": 0.05,
            "conflict_min_center_density": 0.08,
            "resolve_single_choice_conflicts": True,
            "conflict_min_gap": 5,
            "conflict_min_delta_from_blank": 12,
            "conflict_auto_resolve_min_confidence": 0.8,
            "conflict_review_min_confidence": 0.65,
            "weak_fill_auto_resolve_min_confidence": 0.8,
            "weak_fill_review_min_confidence": 0.65,
            "max_mean": 215,
            "supported_field_types": ["QTYPE_MCQ4"],
            "exclude_labels": [],
        },
        "weak_identifier_params": {
            "enabled": False,
            "labels": [],
            "exclude_labels": [],
            "resolve_conflicts": True,
            "conflict_auto_resolve_min_confidence": 0.8,
            "conflict_review_min_confidence": 0.65,
            "min_gap": 20,
            "min_delta_from_blank": 25,
            "adaptive_min_gap": 10,
            "adaptive_min_delta_from_blank": 15,
            "min_page_z_score": 2.0,
            "min_dark_pixel_ratio": 0.06,
            "min_density_gap": 0.02,
            "conflict_use_density": True,
            "conflict_min_density_gap": 0.04,
            "conflict_min_center_density": 0.06,
            "max_mean": 205,
            "adaptive_max_mean": 210,
            "supported_field_types": ["QTYPE_INT"],
        },
        "weak_multi_mark_params": {
            "enabled": False,
            "labels": [],
            "only_when_blank": True,
            "min_delta_from_blank": 10,
            "max_mean": 218,
            "max_marks": 4,
            "filter_use_density": True,
            "filter_min_center_density": 0.18,
            "filter_min_density_gap": 0.08,
            "full_select_min_center_density": 0.35,
            "full_select_max_density_spread": 0.35,
            "full_select_fallback_enabled": False,
            "full_select_max_mean": 170,
            "full_select_min_delta_from_blank": 35,
            "full_select_max_spread": 25,
        },
        "outputs": {
            "show_image_level": 0,
            "save_image_level": 0,
            "save_detections": True,
            "filter_out_multimarked_files": False,
        },
    },
    _dynamic=False,
)
